from console import *
from Transaction import *
import Queue
if __name__ == "__main__":
    # nodeone = node()
    # newblock = utils.create_genesis_block()
    # print(newblock)
    # nodeone.blockchain.append(newblock)
    # print(nodeone.blockchain)
    # start_time = time.time()
    # blocktwo = nodeone.mining([])
    # print("--- %s seconds ---" % (time.time() - start_time))
    # print(blocktwo)
    # print(blocktwo.calculate_hash())
    # console(8001).register()
    # console(8002).register()
    # console(8003).register()
    # console(8004).register()
    # console(8005).register()
    # tx = transaction('1','1',10, '1')
    # print(tx)
    console(8001).register()
    console(8002).register()
    console(8003).register()
    console(8001).transfer('8002', 10, 3)
    console(8002).transfer('8001', 5, 2)
    console(8003).transfer('8002', 4, 2)
    # q = Queue.PriorityQueue()
    # tx1 = transaction('1','2',10, 2)
    # tx2 = transaction('2','1',10, 1)
    # print(tx1)
    # print(tx2)
    # q.put(tx1)
    # q.put(tx2)
    # while not q.empty():
	#     print q.get()